"""German text for the /de/ pages, as (English source, German) pairs."""

PAIRS = [
    (">Skip to content<", ">Zum Inhalt springen<"),
    ('aria-label="Main"', 'aria-label="Hauptmenü"'),
    (">Games</a>", ">Spiele</a>"),
    (">Press<", ">Presse<"),
    (">Contact<", ">Kontakt<"),
    ('aria-label="Games"', 'aria-label="Spiele"'),
    ('aria-label="Elsewhere"', 'aria-label="Anderswo"'),
    ('aria-label="Follow"', 'aria-label="Folgen"'),
    (">Imprint<", ">Impressum<"),
    (">Privacy<", ">Datenschutz<"),
    ("An independent game studio in Tyrol, Austria.", "Ein unabhängiges Spielestudio in Tirol, Österreich."),
    ('aria-label="Play clip"', 'aria-label="Clip abspielen"'),
    ('aria-label="Close"', 'aria-label="Schließen"'),
    ('aria-label="Previous screenshot"', 'aria-label="Vorheriger Screenshot"'),
    ('aria-label="Next screenshot"', 'aria-label="Nächster Screenshot"'),
    ("Wishlist on Steam", "Auf die Steam-Wunschliste"),
    (">Play the free demo<", ">Kostenlose Demo spielen<"),
    (">Out 9 November 2026<", ">Erscheint am 9. November 2026<"),
    (">Coming soon<", ">Demnächst<"),
    (">Release<", ">Erscheint<"),
    (">9 November 2026<", ">9. November 2026<"),
    (">Price<", ">Preis<"),
    (">To be announced<", ">Wird noch bekannt gegeben<"),
    (">Platforms<", ">Plattformen<"),
    (">Languages<", ">Sprachen<"),
    (">Controls<", ">Steuerung<"),
    (">Made with<", ">Gemacht mit<"),
    (">Developer<", ">Entwickler<"),
    (">Steam page ", ">Steam-Seite "),
    (">Free demo ", ">Kostenlose Demo "),
    (">Press kit ", ">Pressekit "),
    (">Also by Loerting Games<", ">Mehr von Loerting Games<"),
    ("Wishlist it on Steam to hear the moment it comes out, or follow along on the channels below.",
     "Setz es auf deine Steam-Wunschliste, dann erfährst du sofort, wenn es erscheint, oder bleib über die Kanäle unten auf dem Laufenden."),
    ("31, including English, German, French, Spanish, Japanese and Chinese",
     "31, darunter Deutsch, Englisch, Französisch, Spanisch, Japanisch und Chinesisch"),
    ("29, including English, German, French, Spanish, Japanese and Chinese",
     "29, darunter Deutsch, Englisch, Französisch, Spanisch, Japanisch und Chinesisch"),
    ("How it plays", "So spielt es sich"),
    ("An automation roguelike where every run fits in one sitting. Out on Steam 9 November 2026, with a free demo now.",
     "Ein Automation-Roguelike, bei dem jeder Run in eine Sitzung passt. Erscheint am 9. November 2026 auf Steam, die Demo gibt es schon jetzt."),
    ("An incremental game about destroying money. Out on Steam 9 November 2026, with a free demo now.",
     "Ein Incremental Game, in dem du Geld zerstörst. Erscheint am 9. November 2026 auf Steam, die Demo gibt es schon jetzt."),
    ("Program fish to explore the deepest trench on Earth, and find out what sank the ship at the bottom.",
     "Programmiere Fische, erkunde den tiefsten Graben der Erde und finde heraus, was das Schiff am Grund versenkt hat."),
    ("An automation roguelike where every run fits in one sitting.",
     "Ein Automation-Roguelike, bei dem jeder Run in eine Sitzung passt."),
    ("An incremental game about destroying money.", "Ein Incremental Game, in dem du Geld zerstörst."),
    ("Program fish to explore the deepest trench on Earth.", "Programmiere Fische und erkunde den tiefsten Graben der Erde."),
    ("Program fish to explore the deepest trench on Earth, using blocks that read like plain English.",
     "Programmiere Fische, die den tiefsten Graben der Erde erkunden, mit Blöcken, die sich wie einfache deutsche Sätze lesen."),
    ("Read the code of the hunters down there and improve your own programs.",
     "Lies den Code der Jäger dort unten und verbessere deine eigenen Programme."),

    ("Loerting Games is an independent game studio in Tyrol, Austria, making Vena, What the Buck?! and Fish Don't Return.",
     "Loerting Games ist ein unabhängiges Spielestudio in Tirol, Österreich, und macht Vena, What the Buck?! und Fish Don't Return."),
    ("An independent game studio in Tyrol, Austria, making Vena, What the Buck?! and Fish Don't Return.",
     "Ein unabhängiges Spielestudio in Tirol, Österreich, das Vena, What the Buck?! und Fish Don't Return macht."),
    ("Games where you build something and <em>watch it run</em>.",
     "Spiele, in denen du etwas baust und <em>zusiehst, wie es läuft</em>."),
    ("Loerting Games is an independent studio in Tyrol, Austria.",
     "Loerting Games ist ein unabhängiges Studio in Tirol, Österreich."),
    (">About the studio<", ">Über das Studio<"),
    ("<strong>Loerting Games</strong> was founded by Leonhard Kohl-Lörting, who studied computer science at the University of Innsbruck.",
     "<strong>Loerting Games</strong> wurde von Leonhard Kohl-Lörting gegründet, der an der Universität Innsbruck Informatik studiert hat."),
    ("Vena started as a game jam prototype that won Godot Wild Jam #85. It comes out on Steam on 9 November 2026, the same day as What the Buck?!, an incremental game about destroying money. Both have a free demo on Steam now. Fish Don’t Return, a programming game set in the Mariana Trench, comes after them.",
     "Vena begann als Prototyp für einen Game Jam und hat den Godot Wild Jam #85 gewonnen. Das Spiel erscheint am 9. November 2026 auf Steam, am selben Tag wie What the Buck?!, ein Incremental Game, in dem du Geld zerstörst. Von beiden gibt es schon jetzt eine kostenlose Demo auf Steam. Danach folgt Fish Don’t Return, ein Programmierspiel im Marianengraben."),
    ("For press, review keys or anything else, ", "Für Presseanfragen, Review-Keys oder alles andere "),
    (">send an email<", ">schreib eine E-Mail<"),

    ("Vena · An automation roguelike · Loerting Games", "Vena · Ein Automation-Roguelike · Loerting Games"),
    ("Vena is an automation roguelike where every run fits in one sitting. Place hexagonal tiles, roll dice in the shop and survive nine phases. Out on Steam 9 November 2026.",
     "Vena ist ein Automation-Roguelike, bei dem jeder Run in eine Sitzung passt. Platziere sechseckige Kacheln, würfle im Shop und überstehe neun Phasen. Erscheint am 9. November 2026 auf Steam."),
    ("An automation roguelike where every run fits in one sitting. Out on Steam 9 November 2026.",
     "Ein Automation-Roguelike, bei dem jeder Run in eine Sitzung passt. Erscheint am 9. November 2026 auf Steam."),
    ("An automation roguelike where every run fits in one sitting. Place hexagonal tiles to grow a production organism, roll dice in the shop and survive nine phases as the Nexus gets hungrier.",
     "Ein Automation-Roguelike, bei dem jeder Run in eine Sitzung passt. Platziere sechseckige Kacheln, lass daraus einen Produktionsorganismus wachsen, würfle im Shop und überstehe neun Phasen, während der Nexus immer hungriger wird."),
    (">Windows, macOS, Linux and Steam Deck<", ">Windows, macOS, Linux und Steam Deck<"),
    ('aria-label="Vena release window trailer"', 'aria-label="Trailer zu Vena"'),
    ("The depth of an automation game, in self-contained roguelike runs of <em>15 to 50 minutes</em>.",
     "Die Tiefe eines Automation-Spiels, in abgeschlossenen Roguelike-Runs von <em>15 bis 50 Minuten</em>."),
    (">How a run goes<", ">So läuft ein Run<"),
    ("Tiles being placed on a hex map, filling a hole next to a vein",
     "Kacheln werden auf die Hex-Karte gesetzt und füllen ein Loch neben einer Vene"),
    (">Feed the Nexus<", ">Versorge den Nexus<"),
    ("You start with the Nexus and the six veins reaching out from it. Chain converters, duplicate producers and gamble on risky tiles to keep up with a demand that grows every phase.",
     "Du beginnst mit dem Nexus und den sechs Venen, die von ihm ausgehen. Verkette Konverter, verdopple Produzenten und setze auf riskante Kacheln, um mit dem Bedarf mitzuhalten, der mit jeder Phase wächst."),
    ("The dice shop, with three dice rolled for new tiles", "Der Würfelladen mit drei geworfenen Würfeln für neue Kacheln"),
    (">Roll for your tiles<", ">Würfle um deine Kacheln<"),
    ("After every phase you buy tiles by rolling dice. Hold and reroll to hunt for the combination you need, or hit a perfect triplet to unlock a fourth die and break the economy.",
     "Nach jeder Phase kaufst du Kacheln, indem du würfelst. Halte Würfel und würfle neu, bis die Kombination passt, oder triff einen perfekten Drilling, der einen vierten Würfel freischaltet und die Wirtschaft sprengt."),
    ("Choosing one of three perks at the end of the shop", "Auswahl eines von drei Perks am Ende des Shops"),
    (">Pick a perk<", ">Wähle einen Perk<"),
    ("Each shop ends with a choice of three perks. Some bend the rules, some open up strategies you would never try otherwise.",
     "Jeder Shop endet mit einer Wahl aus drei Perks. Manche dehnen die Regeln, andere eröffnen Strategien, die du sonst nie ausprobieren würdest."),
    (">What’s in it<", ">Was drinsteckt<"),
    ("Easy to pick up and hard to master. Expect a hundred hours or more to see all of it.",
     "Schnell gelernt, schwer zu meistern. Bis du alles gesehen hast, vergehen gut hundert Stunden."),
    (">In Vena, you can<", ">In Vena kannst du<"),
    ("Try to break the game with wild strategies and hunt for the perfect synergy.",
     "Das Spiel mit wilden Strategien sprengen und die perfekte Synergie suchen."),
    ("Optimise your organism by reading the statistics and refining its flow and layout.",
     "Deinen Organismus optimieren, indem du die Statistiken liest und Fluss und Layout verfeinerst."),
    ("Get better every run. No two are the same, since every session makes you adapt to new perks and tiles.",
     "Mit jedem Run besser werden. Keiner gleicht dem anderen, weil du dich jedes Mal an neue Perks und Kacheln anpassen musst."),
    ("Progress through seven game modes and five difficulty tiers.",
     "Dich durch sieben Spielmodi und fünf Schwierigkeitsstufen arbeiten."),
    ("Relax to sound design composed with world instruments, and take in the detailed pixel art.",
     "Beim Sounddesign mit Instrumenten aus aller Welt entspannen und die detaillierte Pixel-Art genießen."),
    ("Build the perfect map without any goals in Sandbox mode, or take on the toughest challenge.",
     "Im Sandbox-Modus ohne Ziel die perfekte Karte bauen oder dich an die schwerste Herausforderung wagen."),
    (">Vena contains<", ">Vena enthält<"),
    ("85+ rotatable hex tiles across five rarities (base, common, rare, mythic and legendary), each with its own effect and its own pixel artwork.",
     "Über 85 drehbare Hex-Kacheln in fünf Seltenheitsstufen (Basis, Gewöhnlich, Selten, Mythisch und Legendär), jede mit eigenem Effekt und eigener Pixel-Art."),
    ("92+ perks that break the rules, enable wild strategies or unlock powerful abilities.",
     "Über 92 Perks, die Regeln brechen, wilde Strategien möglich machen oder starke Fähigkeiten freischalten."),
    ("20+ unlockable skins, earned by completing challenges and beating high difficulties.",
     "Über 20 freischaltbare Skins, die du dir mit Herausforderungen und hohen Schwierigkeitsgraden verdienst."),
    ("Seven game modes and five difficulties, all of them playable as Endless runs.",
     "Sieben Spielmodi und fünf Schwierigkeitsgrade, alle auch als Endlos-Run spielbar."),
    ("Manage your resources and survive all nine phases.", "Verwalte deine Ressourcen und überstehe alle neun Phasen."),
    ("Infinite resources and no doom. Build the perfect organism.", "Unendliche Ressourcen, kein Untergang. Bau den perfekten Organismus."),
    ("<strong>Compact</strong>", "<strong>Kompakt</strong>"),
    ("A shorter session on a small map with a reduced deck.", "Eine kürzere Sitzung auf einer kleinen Karte mit reduziertem Basis-Deck."),
    ("<strong>Star</strong>", "<strong>Stern</strong>"),
    ("A star-shaped map that asks for different planning.", "Eine sternförmige Karte, die anders geplant werden will."),
    ("<strong>Islands</strong>", "<strong>Inseln</strong>"),
    ("Six separate map pieces, joined through portals.", "Sechs getrennte Kartenteile, verbunden durch Portale."),
    ("<strong>Spiral</strong>", "<strong>Spirale</strong>"),
    ("Build along a spiral out from the centre.", "Baue entlang einer Spirale, die sich aus der Mitte windet."),
    ("<strong>Daily</strong>", "<strong>Täglich</strong>"),
    ("New starting conditions every day.", "Jeden Tag neue Startbedingungen."),
    ("<strong>Endless</strong>", "<strong>Endlos</strong>"),
    ("Every mode can keep going after the last phase.", "Jeder Modus kann nach der letzten Phase weiterlaufen."),
    ("A large organism of tiles spreading across the map", "Ein großer Organismus aus Kacheln, der sich über die Karte ausbreitet"),
    ("Islands of tiles connected by red veins", "Inseln aus Kacheln, verbunden durch rote Venen"),
    ("The dice shop between phases", "Der Würfelladen zwischen zwei Phasen"),
    ("A dense late-game map with a legendary tile selected", "Eine dicht bebaute Karte spät im Run, eine legendäre Kachel ist ausgewählt"),
    ("A long chain of tiles on the Spiral map", "Eine lange Kette aus Kacheln auf der Karte Spirale"),
    ('alt="Choosing a perk"', 'alt="Auswahl eines Perks"'),
    ("Production statistics for the Monolith tile", "Produktionsstatistik der Monolith-Kachel"),
    ("The base deck drawn at the start of every phase", "Das Basis-Deck, das zu Beginn jeder Phase gezogen wird"),
    ("Game mode selection with the Islands map", "Auswahl des Spielmodus mit der Karte Inseln"),
    ("Choosing a skin for the Nexus", "Auswahl eines Skins für den Nexus"),
    (">View all 10 screenshots<", ">Alle 10 Screenshots ansehen<"),
    (">Mouse, controller or touch<", ">Maus, Controller oder Touch<"),
    (">Accessibility<", ">Barrierefreiheit<"),
    ("Reduced visual load, a static background, rebindable controls and a hyperlegible font",
     "Weniger visuelle Reize, ein statischer Hintergrund, frei belegbare Steuerung und eine besonders gut lesbare Schrift"),
    (">Follow Vena<", ">Vena folgen<"),

    ("What the Buck?! · An incremental game · Loerting Games", "What the Buck?! · Ein Incremental Game · Loerting Games"),
    ("What the Buck?! is an incremental game about destroying money. Smash stacks of cash, upgrade your destructive power, discover skill tree upgrades and prestige. Out on Steam 9 November 2026.",
     "What the Buck?! ist ein Incremental Game, in dem du Geld zerstörst. Zerschmettere Geldstapel, verbessere deine Zerstörungskraft, entdecke Skilltree-Upgrades und nutze das Prestige-System. Erscheint am 9. November 2026 auf Steam."),
    ("An incremental game about destroying money. Out on Steam 9 November 2026.",
     "Ein Incremental Game, in dem du Geld zerstörst. Erscheint am 9. November 2026 auf Steam."),
    ("An incremental game about destroying money. Smash stacks of cash, upgrade your destructive power, discover game-changing skill tree upgrades and prestige.",
     "Ein Incremental Game, in dem du Geld zerstörst. Zerschmettere Geldstapel, verbessere deine Zerstörungskraft, entdecke Skilltree-Upgrades, die das Spiel verändern, und nutze das Prestige-System."),
    (">Windows, macOS and Linux<", ">Windows, macOS und Linux<"),
    ('aria-label="What the Buck?! demo trailer"', 'aria-label="Demo-Trailer zu What the Buck?!"'),
    ("Smash stacks of cash, upgrade your destructive power and watch the <em>numbers explode</em>.",
     "Zerschmettere Geldstapel, verbessere deine Zerstörungskraft und sieh zu, wie die <em>Zahlen explodieren</em>."),
    ("An upgrade that increases the breaker strike radius from 5 to 9 pixels",
     "Ein Upgrade, das den Aktionsradius des Schredders von 5 auf 9 Pixel vergrößert"),
    (">Buy upgrades<", ">Kaufe Upgrades<"),
    ("Spend your funds on the breaker’s radius, damage, speed and critical hits, or on withdrawing more and bigger bills.",
     "Steck dein Guthaben in Radius, Schaden, Tempo und kritische Treffer des Schredders oder darin, mehr und größere Scheine abzuheben."),
    ("Bills and coins bursting apart on the table as the earnings pop up",
     "Scheine und Münzen zerspringen auf dem Tisch, darüber tauchen die Einnahmen auf"),
    (">Smash stacks of cash<", ">Zerstöre Geldstapel<"),
    ("Bills and coins pile up on the table, and every strike of the breaker blows them apart. The more you destroy, the faster the numbers climb.",
     "Scheine und Münzen stapeln sich auf dem Tisch, und jeder Schredder-Schlag sprengt sie auseinander. Je mehr du zerstörst, desto schneller steigen die Zahlen."),
    ("The skill tree growing as upgrades are bought", "Der Skilltree wächst, während Upgrades gekauft werden"),
    (">Use the prestige system<", ">Nutze das Prestige-System<"),
    ("Prestige to grow a skill tree full of game-changing upgrades, from better bills to bills that explode.",
     "Mit Prestige wächst ein Skilltree voller Upgrades, die das Spiel verändern, von besseren Scheinen bis zu Scheinen, die explodieren."),
    ("Lightning strikes crackle across a table of cash as 26.4K dollars come in",
     "Blitze zucken über einen Tisch voller Geld, während 26,4K Dollar hereinkommen"),
    ("Stacks of bills and coins bursting apart on the table", "Stapel aus Scheinen und Münzen zerspringen auf dem Tisch"),
    ("The skill tree with the Volatile Bills upgrade selected", "Der Skilltree mit einem ausgewählten Upgrade für explosive Scheine"),
    ("Golden bills piling up on the table", "Goldene Scheine stapeln sich auf dem Tisch"),
    ("The skill tree before a new shift starts", "Der Skilltree, bevor eine neue Schicht beginnt"),
    (">Mouse or touch<", ">Maus oder Touch<"),
    (">Follow What the Buck?!<", ">What the Buck?! folgen<"),

    ("Fish Don't Return · A programming game in the Mariana Trench · Loerting Games",
     "Fish Don't Return · Ein Programmierspiel im Marianengraben · Loerting Games"),
    ("Program fish to explore the deepest trench on Earth, using blocks that read like plain English. Read the code of the hunters down there, and find out what sank the ship at the bottom.",
     "Programmiere Fische mit Blöcken, die sich wie einfache deutsche Sätze lesen, und erkunde den tiefsten Graben der Erde. Lies den Code der Jäger dort unten und finde heraus, was das Schiff am Grund versenkt hat."),
    ("You buy a fish, give it a program made of blocks and drop it into the sea. From there on it is <em>on its own</em>.",
     "Du kaufst einen Fisch, gibst ihm ein Programm aus Blöcken und lässt ihn ins Meer fallen. Ab dann ist er <em>auf sich allein gestellt</em>."),
    ("A fish follows its program towards a coin while the program is open beside it",
     "Ein Fisch folgt seinem Programm zu einer Münze, daneben ist das Programm geöffnet"),
    (">Programs you can read out loud<", ">Programme zum Vorlesen<"),
    ("Every block reads like part of a sentence, and blocks snap together, so there is nothing to type and no syntax to get wrong. If you have never written a program before, this is a good place to start.",
     "Jeder Block liest sich wie ein Teil eines Satzes, und Blöcke rasten ineinander ein. Du tippst nichts und kannst keine Syntax falsch machen. Wer noch nie programmiert hat, kann hier gut anfangen."),
    ("A fish bumps a lionfish from behind, where the lionfish cannot bite",
     "Ein Fisch rammt einen Rotfeuerfisch von hinten, wo der nicht zubeißen kann"),
    (">Hunters run programs too<", ">Auch die Jäger haben Programme<"),
    ("The trench’s hunters are written in the same blocks. Click one and its program opens, so you can read what it will do before your fish meets it. Then write a fish that slips past it, or one that attacks it from behind.",
     "Die Jäger im Graben sind aus denselben Blöcken gebaut. Klick einen an, und sein Programm öffnet sich. So liest du, was er tun wird, bevor dein Fisch ihm begegnet. Dann schreib einen Fisch, der an ihm vorbeischlüpft, oder einen, der ihn von hinten angreift."),
    ("A lantern fish sinks through the veil at the Mouth, where the safe water ends",
     "Ein Laternenfisch sinkt an der Mündung durch den Schleier, wo das sichere Wasser endet"),
    (">Deeper down, you mostly watch<", ">Weiter unten schaust du vor allem zu<"),
    ("Near the surface you can stop a fish and change its program as often as you like. Deeper down that only works inside the light of a violet crystal. Everywhere else it runs as you wrote it.",
     "Nahe der Oberfläche kannst du einen Fisch anhalten und sein Programm so oft ändern, wie du willst. Weiter unten geht das nur im Licht eines violetten Kristalls. Überall sonst läuft es so, wie du es geschrieben hast."),
    ("The wreck of the Nadir on the sea floor, her searchlight sweeping the dark",
     "Das Wrack der Nadir am Meeresgrund, ihr Suchscheinwerfer streicht durch die Dunkelheit"),
    ("What happened to the <i>Nadir</i>?", "Was ist mit der <i>Nadir</i> passiert?"),
    ("At the bottom of the trench lies a ship broken in two. She went down in 1966. Her searchlight still sweeps the dark, and when one of your fish comes near, the beam stops and stays on it.",
     "Am Grund des Grabens liegt ein Schiff, in zwei Teile zerbrochen. Es ist die Nadir, gesunken 1966. Ihr Suchscheinwerfer streicht noch immer durch die Dunkelheit, und wenn einer deiner Fische näherkommt, bleibt der Strahl auf ihm stehen."),
    ("Her anchor is still down there, on the sand not far below the surface. When one of your fish reaches it, you read:",
     "Ihr Anker liegt noch dort unten im Sand, nicht weit unter der Oberfläche. Wenn einer deiner Fische ihn erreicht, liest du:"),
    ("“Heavy enough to hold a ship through any storm. So where is the ship?”",
     "„Schwer genug, um ein Schiff durch jeden Sturm zu halten. Wo ist dann das Schiff?“"),
    ("Each piece of her your fish reach adds a line or two, and read in order they tell what happened. There is an ending for whoever gets that far.",
     "Jedes Stück von ihr, das deine Fische erreichen, bringt ein, zwei Zeilen dazu, und der Reihe nach gelesen erzählen sie, was passiert ist. Für alle, die so weit kommen, gibt es ein Ende."),
    ("A fish’s program open on the glass: if I see a coin, turn towards it and swim, else rotate 30 degrees right",
     "Das Programm eines Fisches, offen auf dem Glas: Wenn ich eine Münze sehe, dreh dich zu ihr und schwimm, sonst dreh dich 30 Grad nach rechts"),
    ("The whale fall in the Boneyard under its arch of coins, with the sleeper shark above it",
     "Der Walkadaver unter seinem Bogen aus Münzen, darüber der Schlafhai"),
    ("A lionfish’s own program open beside it while it stares at a coin",
     "Das Programm eines Rotfeuerfisches, geöffnet neben ihm, während er eine Münze anstarrt"),
    ("The Nadir on the sea floor, her searchlight turned onto a fish over her deck",
     "Die Nadir am Meeresgrund, ihr Suchscheinwerfer auf einen Fisch über ihrem Deck gerichtet"),
    ("A fish dropped into the sea goes nose first through the swell",
     "Ein Fisch fällt ins Meer und taucht mit der Nase voran durch die Dünung"),
    ("The marlin raises its sail for the second before it charges",
     "Der Marlin stellt für eine Sekunde sein Segel auf, bevor er angreift"),
    ("A chest opened, the new block flying up to the logbook",
     "Eine geöffnete Truhe, der neue Block fliegt hinauf ins Logbuch"),
    ("A parachute caught on a chimney in the Vent Field", "Ein Fallschirm, verfangen an einem Schlot zwischen den heißen Quellen"),
    ("An anglerfish waiting in the dark with its lure lit", "Ein Anglerfisch wartet im Dunkeln mit leuchtendem Köder"),
    ("A fish stopped in a crystal’s violet light, its program open to be changed",
     "Ein Fisch im violetten Licht eines Kristalls, sein Programm ist zum Ändern geöffnet"),
    ("A lost fish lying by the chest it swam for", "Ein verlorener Fisch liegt neben der Truhe, zu der er geschwommen ist"),
    ("The bright shallows under the swell, with a school turning", "Das helle Flachwasser unter der Dünung, ein Fischschwarm dreht ab"),
    (">View all 12 screenshots<", ">Alle 12 Screenshots ansehen<"),
    (">English, German to follow<", ">Englisch, Deutsch folgt<"),
    (">Mouse and keyboard<", ">Maus und Tastatur<"),
    (">Players<", ">Spieler<"),
    (">Single-player, offline<", ">Einzelspieler, offline<"),
    (">Music<", ">Musik<"),
    ("A piano piece for every depth, played by the developer and set for strings",
     "Ein Klavierstück für jede Tiefe, vom Entwickler eingespielt und für Streicher gesetzt"),
    (">Still in development<", ">Noch in Entwicklung<"),
    ("Wishlist Fish Don’t Return on Steam to hear when there is a demo and when it comes out.",
     "Setz Fish Don’t Return auf deine Steam-Wunschliste, dann erfährst du, wann es eine Demo gibt und wann das Spiel erscheint."),
    ("<span>PDF, 5.0 MB</span>", "<span>PDF, 5,0 MB</span>"),
    (">Logos and screenshots ", ">Logos und Screenshots "),

    ("Press · Loerting Games", "Presse · Loerting Games"),
    ("Facts, logos, art and screenshots for Vena, What the Buck?! and Fish Don't Return, free to use in coverage.",
     "Fakten, Logos, Artwork und Screenshots zu Vena, What the Buck?! und Fish Don't Return, frei für die Berichterstattung."),
    ('Everything here is free to use in coverage of the games. For review keys, interviews or anything else, write to <a href="#contact" data-mail data-mail-show>the address below</a>.',
     'Alles hier darf frei für Berichte über die Spiele verwendet werden. Für Review-Keys, Interviews oder alles andere schreib an <a href="#contact" data-mail data-mail-show>die Adresse unten</a>.'),
    ('alt="Vena key art"', 'alt="Key-Art von Vena"'),
    ('alt="What the Buck?! key art"', 'alt="Key-Art von What the Buck?!"'),
    ('alt="Fish Don\'t Return key art"', 'alt="Key-Art von Fish Don\'t Return"'),
    (">Automation roguelike<", ">Automation-Roguelike<"),
    (">Free on Steam<", ">Kostenlos auf Steam<"),
    (">Award<", ">Auszeichnung<"),
    (">Winner of Godot Wild Jam #85<", ">Gewinner des Godot Wild Jam #85<"),
    ("An automation roguelike where every run fits in one sitting. Place hexagonal tiles to grow a production organism, roll dice in the shop to buy new ones and pick perks that shape your build. Survive nine phases as the Nexus’s hunger outpaces you.",
     "Ein Automation-Roguelike, bei dem jeder Run in eine Sitzung passt. Platziere sechseckige Kacheln zu einem Produktionsorganismus, würfle im Shop um neue und wähle Perks für deinen Build. Überstehe neun Phasen, während der Hunger des Nexus dich überholt."),
    (">Logos, art and screenshots ", ">Logos, Artwork und Screenshots "),
    ("<span>ZIP, 9.1 MB</span>", "<span>ZIP, 9,1 MB</span>"),
    ("<span>ZIP, 4.4 MB</span>", "<span>ZIP, 4,4 MB</span>"),
    ("<span>ZIP, 10.6 MB</span>", "<span>ZIP, 10,6 MB</span>"),
    (">Game page ", ">Spielseite "),
    (">Incremental<", ">Incremental Game<"),
    ("What the Buck?! is an incremental game about destroying money. Smash stacks of cash, upgrade your destructive power, discover game-changing skill tree upgrades, prestige and experience the dopamine of numbers exploding.",
     "What the Buck?! ist ein Incremental Game, bei dem es darum geht, Geld zu zerstören. Zerschmettere Geldstapel, verbessere deine Zerstörungskraft, entdecke spielverändernde Skilltree-Upgrades, nutze das Prestige-System und erlebe das pure Dopamin explodierender Zahlen."),
    (">Block programming, exploration, mystery<", ">Block-Programmierung, Erkundung, Mystery<"),
    ("Program fish to explore the deepest trench on Earth, using blocks that read like plain English. Read the code of the hunters down there and improve your own programs. Somewhere at the bottom lies the wreck of a ship that sank in 1966.",
     "Programmiere Fische, die den tiefsten Graben der Erde erkunden, mit Blöcken, die sich wie einfache deutsche Sätze lesen. Lies den Code der Jäger dort unten und verbessere deine eigenen Programme. Irgendwo am Grund liegt das Wrack eines Schiffes, das 1966 gesunken ist."),
    (">The studio<", ">Das Studio<"),
    (">Founder<", ">Gründer<"),
    (">Based in<", ">Sitz<"),
    (">Tyrol, Austria<", ">Tirol, Österreich<"),
    ("Loerting Games is an independent game studio in Tyrol, Austria, founded by Leonhard Kohl-Lörting, who studied computer science at the University of Innsbruck. Vena grew out of a game jam prototype and is the studio’s first commercial release.",
     "Loerting Games ist ein unabhängiges Spielestudio in Tirol, Österreich, gegründet von Leonhard Kohl-Lörting, der an der Universität Innsbruck Informatik studiert hat. Vena ist aus einem Game-Jam-Prototyp entstanden und die erste kommerzielle Veröffentlichung des Studios."),
    (">Email (needs JavaScript)<", ">E-Mail (braucht JavaScript)<"),

    ("Imprint and Privacy · Loerting Games", "Impressum und Datenschutz · Loerting Games"),
    ("Imprint (Impressum) and privacy notice for the Loerting Games website.", "Impressum und Datenschutzerklärung der Website von Loerting Games."),
    (">Imprint and privacy<", ">Impressum und Datenschutz<"),
    ('Imprint <span lang="de">(Impressum)</span>', "Impressum"),
    ("Information according to § 5 ECG and disclosure according to § 25 MedienG.",
     "Angaben gemäß § 5 ECG und Offenlegung gemäß § 25 MedienG."),
    ("6063 Rum, Austria", "6063 Rum, Österreich"),
    ("<p>Email: ", "<p>E-Mail: "),
    (">shown with JavaScript turned on<", ">wird mit aktiviertem JavaScript angezeigt<"),
    ("Business: development and publishing of video games under the name Loerting Games.",
     "Unternehmensgegenstand: Entwicklung und Veröffentlichung von Videospielen unter dem Namen Loerting Games."),
    ("Media owner and publisher: Leonhard Kohl-Lörting. This website gives information about the games Vena, What the Buck?! and Fish Don’t Return.",
     "Medieninhaber und Herausgeber: Leonhard Kohl-Lörting. Diese Website informiert über die Spiele Vena, What the Buck?! und Fish Don’t Return."),
    ("This website does not use cookies, analytics or tracking of any kind, and it loads nothing from other companies’ servers. Fonts, pictures and videos are served from this site itself.",
     "Diese Website verwendet keine Cookies, keine Analyse und kein Tracking und lädt nichts von Servern anderer Unternehmen. Schriften, Bilder und Videos kommen direkt von dieser Website."),
    ('The site is hosted on GitHub Pages, a service of GitHub, Inc. (88 Colin P Kelly Jr St, San Francisco, CA 94107, USA). GitHub states that when a GitHub Pages site is visited, the visitor’s IP address is logged and stored for security purposes. The legal basis is the legitimate interest in running a secure website (Art. 6(1)(f) GDPR). See the <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub Privacy Statement</a> for details.',
     'Die Website wird auf GitHub Pages gehostet, einem Dienst von GitHub, Inc. (88 Colin P Kelly Jr St, San Francisco, CA 94107, USA). Laut GitHub wird beim Aufruf einer GitHub-Pages-Seite die IP-Adresse der Besucher aus Sicherheitsgründen protokolliert und gespeichert. Rechtsgrundlage ist das berechtigte Interesse am sicheren Betrieb der Website (Art. 6 Abs. 1 lit. f DSGVO). Näheres steht im <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub Privacy Statement</a>.'),
    (">Email<", ">E-Mail<"),
    ("If you write an email, your address and message are used only to answer you and are not passed on.",
     "Wenn du eine E-Mail schreibst, werden deine Adresse und deine Nachricht nur verwendet, um dir zu antworten, und nicht weitergegeben."),
    (">Links to other sites<", ">Links zu anderen Seiten<"),
    ("Links to Steam, Discord and the social networks lead to services run by other companies. Their privacy policies apply once you follow a link.",
     "Links zu Steam, Discord und den sozialen Netzwerken führen zu Diensten anderer Unternehmen. Sobald du einem Link folgst, gilt deren Datenschutzerklärung."),
    (">Your rights<", ">Deine Rechte<"),
    ('You have the right to access, correct, delete and restrict the processing of your personal data, to data portability and to object. To use them, write to the address above. You can also lodge a complaint with the Austrian data protection authority, the <a href="https://www.dsb.gv.at/" lang="de">Datenschutzbehörde</a>.',
     'Du hast das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung deiner personenbezogenen Daten, auf Datenübertragbarkeit und auf Widerspruch. Schreib dafür an die Adresse oben. Beschweren kannst du dich auch bei der österreichischen <a href="https://www.dsb.gv.at/">Datenschutzbehörde</a>.'),

    ("Privacy Policy for Vena · Loerting Games", "Datenschutzerklärung für Vena · Loerting Games"),
    ("What the Android version of Vena does with your data: it collects, transmits and shares none.",
     "Was die Android-Version von Vena mit deinen Daten macht: Sie sammelt, überträgt und teilt keine."),
    (">Privacy Policy for Vena<", ">Datenschutzerklärung für Vena<"),
    (">Last updated: 16 September 2026<", ">Zuletzt aktualisiert: 16. September 2026<"),
    ("Vena (“the game”) is developed and published by Leonhard Kohl-Lörting (“I”, “me”). This policy explains what the Android version of Vena does with your data.",
     "Vena („das Spiel“) wird von Leonhard Kohl-Lörting („ich“) entwickelt und veröffentlicht. Diese Erklärung beschreibt, was die Android-Version von Vena mit deinen Daten macht."),
    (">Short version<", ">Kurzfassung<"),
    ("Vena does not collect, transmit or share any personal data. It has no accounts, no advertising, no analytics and no tracking. It does not need an internet connection to play.",
     "Vena sammelt, überträgt und teilt keine personenbezogenen Daten. Es gibt keine Konten, keine Werbung, keine Analyse und kein Tracking. Zum Spielen braucht Vena keine Internetverbindung."),
    (">Data stored on your device<", ">Daten auf deinem Gerät<"),
    ("Vena saves the following locally, in the app’s private storage:", "Vena speichert Folgendes lokal im privaten Speicher der App:"),
    (">your game progress and save files<", ">deinen Spielfortschritt und deine Spielstände<"),
    (">your settings (language, audio volume, controls, graphics options)<", ">deine Einstellungen (Sprache, Lautstärke, Steuerung, Grafikoptionen)<"),
    (">your unlocked skins and achievements<", ">deine freigeschalteten Skins und Errungenschaften<"),
    (">screenshots you choose to take with the in-game screenshot function<", ">Screenshots, die du selbst mit der Screenshot-Funktion im Spiel aufnimmst<"),
    ("This data never leaves your device. It is not readable by me or by anyone else. If you uninstall Vena, Android deletes it along with the app.",
     "Diese Daten verlassen dein Gerät nie. Weder ich noch sonst jemand kann sie lesen. Wenn du Vena deinstallierst, löscht Android sie zusammen mit der App."),
    (">Data sent off your device<", ">Daten, die dein Gerät verlassen<"),
    ("None. Vena makes no network requests of its own and contains no advertising, analytics, crash-reporting or attribution SDKs.",
     "Keine. Vena stellt selbst keine Netzwerkanfragen und enthält keine SDKs für Werbung, Analyse, Absturzberichte oder Attribution."),
    (">Links that open outside the game<", ">Links, die sich außerhalb des Spiels öffnen<"),
    ("Vena has buttons that open external pages in your browser or in another app. Opening one is always your choice, and once you leave the game you are covered by that service’s own privacy policy, not this one. Those destinations are:",
     "Vena hat Schaltflächen, die externe Seiten in deinem Browser oder in einer anderen App öffnen. Ob du eine davon öffnest, entscheidest immer du, und sobald du das Spiel verlässt, gilt die Datenschutzerklärung des jeweiligen Dienstes, nicht diese. Die Ziele sind:"),
    (">a Google Forms feedback form, if you choose to send feedback. Anything you type into that form is processed by Google under Google’s privacy policy.<",
     ">ein Feedback-Formular von Google Forms, falls du Feedback senden willst. Was du dort eingibst, verarbeitet Google nach seiner eigenen Datenschutzerklärung.<"),
    (">Purchases<", ">Käufe<"),
    ("Vena is a paid app. Your purchase, and any free trial offered through Google Play, is handled entirely by Google Play. I never see your payment details. Google’s handling of that transaction is covered by the Google Play Terms of Service and Google’s privacy policy.",
     "Vena ist eine kostenpflichtige App. Den Kauf und eine eventuelle Testphase wickelt vollständig Google Play ab. Deine Zahlungsdaten sehe ich nie. Für die Abwicklung durch Google gelten die Nutzungsbedingungen von Google Play und die Datenschutzerklärung von Google."),
    (">Children<", ">Kinder<"),
    ("Vena contains no data collection, no ads and no social features, so there is nothing for it to collect from anyone, including children under 13.",
     "Vena sammelt keine Daten, zeigt keine Werbung und hat keine sozialen Funktionen. Es gibt also nichts, was Vena von irgendwem sammeln könnte, auch nicht von Kindern unter 13."),
    (">Changes<", ">Änderungen<"),
    ("If this policy ever changes, the updated version will be posted at this URL and the date at the top will change.",
     "Wenn sich diese Erklärung ändert, erscheint die neue Fassung unter dieser Adresse und das Datum oben ändert sich."),
    ("Questions about this policy:", "Fragen zu dieser Erklärung:"),
    (">email address shown with JavaScript turned on<", ">E-Mail-Adresse wird mit aktiviertem JavaScript angezeigt<"),
]

KEEP = {
    "Loerting Games", "Vena", "What the Buck?!", "Fish Don’t Return", "Fish Don't Return", "Nadir",
    "Steam", "Discord", "YouTube", "Instagram", "TikTok", "X", "Bluesky", "EN", "DE", "English",
    "Screenshots", "Details", "Trailer", "Hosting", "Genre", "Demo", "Studio", "Engine",
    "Standard", "Sandbox", "Godot 4", "kohlgames", "Leonhard Kohl-Lörting", "© 2026 Leonhard Kohl-Lörting",
    "Windows, macOS, Linux, Steam Deck", "Windows, macOS, Linux", "Murstraße 38b", "29", "31",
    "Steam:", "Discord:", "YouTube:", "Instagram:", "store.steampowered.com", "discord.gg",
    "www.youtube.com", "www.instagram.com", "Datenschutzbehörde", "GitHub Privacy Statement",
    "Vena · Loerting Games",
}
